### ISSUE TITLE
I cannot download the Subtitle  this Movie

### ISSUE THREAD

**Issue by MrGamesKingPro** [Tithen-Firion/UserScripts#13]
I cannot download the Subtitle Arabic  this Movie
https://tv.apple.com/eg/movie/the-father/umc.cmc.1737b9sd7muinc2as10iz1w0p

**Comment by Tithen-Firion** [comment]
The link you sent redirects me to <https://tv.apple.com/in/movie/the-father/umc.cmc.1737b9sd7muinc2as10iz1w0p> which shows "This content is no longer available". So obviously subs can't be downloaded from that.

**Comment by Essam311** [comment]
@Tithen-Firion You must use private browsing on Firefox otherwise the links will be directed to the country of your apple TV+ account, or you could sign out from your apple TV+ account to prevent the links from being redirected.

This is the error message that happens when you try to download the subtitles.

![error](https://user-images.githubusercontent.com/59211054/112749478-aafbfb00-8fc2-11eb-94a6-798850add19e.png)

 
![error2](https://user-images.githubusercontent.com/59211054/112749524-1219af80-8fc3-11eb-8c22-26c2a594b3c4.png)



![sub2](https://user-images.githubusercontent.com/59211054/112749243-66239480-8fc1-11eb-9dfe-4ff768a04e26.png)

**Comment by Tithen-Firion** [comment]
Well I guess you have to buy it. Or it's not released yet. There are 11 playlist URLs on that page. After removing duplicates you end up with 5.

For me it was 1 link to the preview of "I, Daniel Blake", 2 to the preview of "The Father" (one has `l=en-GB` in the link, the other `l=en`, basically the same stuff - preview, so no subs), and 2 to the actual video (`aec=HD` and `aec=SD`) - and both return error 404 (Not found). So there's nothing I can do.
